In [ ]:
import numpy as np

Defaulting to user installation because normal site-packages is not writeable


In [ ]:
#Numpy begins
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
#slicing works just like in python
a[1:3]

array([2, 3])

In [ ]:
# Multiple indexing
b[[0,2,1]]

array([5, 7, 6])

In [ ]:
print(a.dtype)
a = np.array([1,2,3,4],dtype=np.int8)
print(a.dtype)

int64
int8


In [ ]:
c = np.array([[1,2,3],
          [4,5,6]
         ])

In [ ]:
c.shape

(2, 3)

In [ ]:
#dimensions
print(c.ndim)
#size
print(c.size)

2
6


In [ ]:
d = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [ ]:
d[1]

array([4, 5, 6])

In [ ]:
d[1,0]

4

In [ ]:
d[1][0]

4

In [ ]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
d.sum()

45

In [ ]:
d.mean()

5.0

In [ ]:
#Verticle
d.sum(axis=0)

array([12, 15, 18])

In [ ]:
#standard deviation, can be taken by axies too
d.std()

2.581988897471611

In [ ]:
#vectorization and Broadcasting
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a+5

array([5, 6, 7, 8])

In [ ]:
a
# note that this didn't affect original array, it created a new array of a+5, to pass it by reference, do a+=5

array([0, 1, 2, 3])

In [ ]:
b = np.array([10,10,10,10])
a+b

array([10, 11, 12, 13])

In [ ]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
e = np.array([[6,5],
                [4,3],
                [2,1]])

In [ ]:
np.dot(d,e)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
d.dot(e)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
d @ e

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
np.cross(d,e)

array([[-15,  18,  -7],
       [-18,  24,  -8],
       [ -9,  18,  -9]])

In [ ]:
#Transpose
d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
#Reshape and linspace are also important concepts